(run format) - working locally, but configs differ in CI
```
ValueError: ('dataset has different config than cfg.dataset_cfg, and allow_dataset_override iscollect_generation_meta', 'args': (), 'kwargs': {} False', "{'applied_filters': {'self': [{'name': '}], 'other': []}}")
```

probably because we are loading a dataset with the new format. will patch but it will be hacky