update maze-dataset dep and poetry lockfile (#213)
* update maze-dataset dep and poetry lockfile

* fixed some imports

* update another import

* another import fix

* hookedtransformer maze tokenizer compat

* update wandb dep

* update transformer_lens dep

* fix import in notebook

* re-ran this notebook. was failing in CI for some reason, idk?

* better error when dataset cfgs dont match

* (run format) - working locally, but configs differ in CI

```
ValueError: ('dataset has different config than cfg.dataset_cfg, and allow_dataset_override iscollect_generation_meta', 'args': (), 'kwargs': {} False', "{'applied_filters': {'self': [{'name': '}], 'other': []}}")
```

probably because we are loading a dataset with the new format. will patch but it will be hacky

* special case for applied filters diff